use ai3;

-- 임의적으로 넣은거라 실제로는 로그인 못해요
INSERT INTO users (username, email, password, address, detail_address, provider) VALUES
('맛집탐험가', 'foodlover1@gmail.com', '$2b$10$N9qo8uLOickgx2ZMRZoMye.IjdJrwQOHdZmQe4rIpOkUmKxcs6MQi', '서울특별시 강남구', '테헤란로 123', 'local'),
('요리왕', 'cookingking@naver.com', '$2b$10$N9qo8uLOickgx2ZMRZoMye.IjdJrwQOHdZmQe4rIpOkUmKxcs6MQi', '부산광역시 해운대구', '해운대해변로 456', 'local'),
('치킨러버', 'chickenlove@daum.net', '$2b$10$N9qo8uLOickgx2ZMRZoMye.IjdJrwQOHdZmQe4rIpOkUmKxcs6MQi', '대구광역시 중구', '중앙대로 789', 'local'),
('피자매니아', 'pizzamania@gmail.com', '$2b$10$N9qo8uLOickgx2ZMRZoMye.IjdJrwQOHdZmQe4rIpOkUmKxcs6MQi', '인천광역시 남동구', '구월동로 321', 'local'),
('라면킬러', 'ramenkiller@naver.com', '$2b$10$N9qo8uLOickgx2ZMRZoMye.IjdJrwQOHdZmQe4rIpOkUmKxcs6MQi', '광주광역시 서구', '상무대로 654', 'local'),
('햄버거헌터', 'burgerhunter@gmail.com', '$2b$10$N9qo8uLOickgx2ZMRZoMye.IjdJrwQOHdZmQe4rIpOkUmKxcs6MQi', '대전광역시 유성구', '대학로 987', 'local'),
('카페인중독', 'coffeeaddict@daum.net', '$2b$10$N9qo8uLOickgx2ZMRZoMye.IjdJrwQOHdZmQe4rIpOkUmKxcs6MQi', '울산광역시 남구', '삼산로 147', 'local'),
('디저트천사', 'dessertangel@gmail.com', '$2b$10$N9qo8uLOickgx2ZMRZoMye.IjdJrwQOHdZmQe4rIpOkUmKxcs6MQi', '경기도 수원시', '영통구 광교로 258', 'local'),
('스시마스터', 'sushimaster@naver.com', '$2b$10$N9qo8uLOickgx2ZMRZoMye.IjdJrwQOHdZmQe4rIpOkUmKxcs6MQi', '경기도 성남시', '분당구 정자로 369', 'local'),
('파스타킹', 'pastaking@gmail.com', '$2b$10$N9qo8uLOickgx2ZMRZoMye.IjdJrwQOHdZmQe4rIpOkUmKxcs6MQi', '경기도 고양시', '일산동구 중앙로 741', 'local'),
('떡볶이왕자', 'tteokbokkiprince@daum.net', '$2b$10$N9qo8uLOickgx2ZMRZoMye.IjdJrwQOHdZmQe4rIpOkUmKxcs6MQi', '경기도 안양시', '만안구 안양로 852', 'local'),
('김치전사', 'kimchiwarrior@gmail.com', '$2b$10$N9qo8uLOickgx2ZMRZoMye.IjdJrwQOHdZmQe4rIpOkUmKxcs6MQi', '경기도 부천시', '원미구 길주로 963', 'local'),
('삼겹살킹', 'samgyeopsalking@naver.com', '$2b$10$N9qo8uLOickgx2ZMRZoMye.IjdJrwQOHdZmQe4rIpOkUmKxcs6MQi', '강원도 춘천시', '중앙로 174', 'local'),
('냉면마니아', 'naengmyeonmania@gmail.com', '$2b$10$N9qo8uLOickgx2ZMRZoMye.IjdJrwQOHdZmQe4rIpOkUmKxcs6MQi', '충청북도 청주시', '상당구 상당로 285', 'local'),
('족발러버', 'jokbalover@daum.net', '$2b$10$N9qo8uLOickgx2ZMRZoMye.IjdJrwQOHdZmQe4rIpOkUmKxcs6MQi', '충청남도 천안시', '동남구 천안대로 396', 'local'),
('순대킹', 'sundaeking@gmail.com', '$2b$10$N9qo8uLOickgx2ZMRZoMye.IjdJrwQOHdZmQe4rIpOkUmKxcs6MQi', '전라북도 전주시', '완산구 전주천동로 417', 'local'),
('갈비천왕', 'galbiking@naver.com', '$2b$10$N9qo8uLOickgx2ZMRZoMye.IjdJrwQOHdZmQe4rIpOkUmKxcs6MQi', '전라남도 광주시', '북구 용봉로 528', 'local'),
('회덮밥마스터', 'hoedeopbapmaster@gmail.com', '$2b$10$N9qo8uLOickgx2ZMRZoMye.IjdJrwQOHdZmQe4rIpOkUmKxcs6MQi', '경상북도 대구시', '달서구 달구벌대로 639', 'local'),
('곱창전문가', 'gopchangexpert@daum.net', '$2b$10$N9qo8uLOickgx2ZMRZoMye.IjdJrwQOHdZmQe4rIpOkUmKxcs6MQi', '경상남도 창원시', '의창구 창원대로 741', 'local'),
('막걸리애호가', 'makgeollilover@gmail.com', '$2b$10$N9qo8uLOickgx2ZMRZoMye.IjdJrwQOHdZmQe4rIpOkUmKxcs6MQi', '제주특별자치도 제주시', '연동로 852', 'local'),
('타코야끼킹', 'takoyakiking@naver.com', '$2b$10$N9qo8uLOickgx2ZMRZoMye.IjdJrwQOHdZmQe4rIpOkUmKxcs6MQi', '서울특별시 마포구', '홍대입구역로 963', 'local'),
('쌀국수러버', 'pholover@gmail.com', '$2b$10$N9qo8uLOickgx2ZMRZoMye.IjdJrwQOHdZmQe4rIpOkUmKxcs6MQi', '서울특별시 종로구', '종로 174', 'local'),
('마라탕중독', 'malatangaddict@daum.net', '$2b$10$N9qo8uLOickgx2ZMRZoMye.IjdJrwQOHdZmQe4rIpOkUmKxcs6MQi', '서울특별시 송파구', '잠실로 285', 'local'),
('훠궈마니아', 'hotpotmania@gmail.com', '$2b$10$N9qo8uLOickgx2ZMRZoMye.IjdJrwQOHdZmQe4rIpOkUmKxcs6MQi', '서울특별시 강서구', '화곡로 396', 'local'),
('볶음밥왕', 'friedriceking@naver.com', '$2b$10$N9qo8uLOickgx2ZMRZoMye.IjdJrwQOHdZmQe4rIpOkUmKxcs6MQi', '부산광역시 부산진구', '서면로 417', 'local'),
('짜장면러버', 'jjajangmyeonlover@gmail.com', '$2b$10$N9qo8uLOickgx2ZMRZoMye.IjdJrwQOHdZmQe4rIpOkUmKxcs6MQi', '부산광역시 동래구', '온천천로 528', 'local'),
('짬뽕킹', 'jjamppongking@daum.net', '$2b$10$N9qo8uLOickgx2ZMRZoMye.IjdJrwQOHdZmQe4rIpOkUmKxcs6MQi', '인천광역시 연수구', '송도국제도시로 639', 'local'),
('탕수육마스터', 'tangsuyukmaster@gmail.com', '$2b$10$N9qo8uLOickgx2ZMRZoMye.IjdJrwQOHdZmQe4rIpOkUmKxcs6MQi', '대구광역시 수성구', '범어로 741', 'local'),
('양꼬치왕', 'yangkkochiking@naver.com', '$2b$10$N9qo8uLOickgx2ZMRZoMye.IjdJrwQOHdZmQe4rIpOkUmKxcs6MQi', '광주광역시 남구', '봉선로 852', 'local'),
('마카롱천사', 'macaronangel@gmail.com', '$2b$10$N9qo8uLOickgx2ZMRZoMye.IjdJrwQOHdZmQe4rIpOkUmKxcs6MQi', '대전광역시 서구', '둔산로 963', 'local'),
('아이스크림킹', 'icecreamking@daum.net', '$2b$10$N9qo8uLOickgx2ZMRZoMye.IjdJrwQOHdZmQe4rIpOkUmKxcs6MQi', '울산광역시 중구', '태화로 174', 'local'),
('와플러버', 'wafflelover@gmail.com', '$2b$10$N9qo8uLOickgx2ZMRZoMye.IjdJrwQOHdZmQe4rIpOkUmKxcs6MQi', '경기도 용인시', '기흥구 용구대로 285', 'local'),
('도넛마니아', 'donutmania@naver.com', '$2b$10$N9qo8uLOickgx2ZMRZoMye.IjdJrwQOHdZmQe4rIpOkUmKxcs6MQi', '경기도 화성시', '동탄순환대로 396', 'local'),
('크로와상킹', 'croissantking@gmail.com', '$2b$10$N9qo8uLOickgx2ZMRZoMye.IjdJrwQOHdZmQe4rIpOkUmKxcs6MQi', '경기도 파주시', '문산읍 임진각로 417', 'local'),
('베이글러버', 'bagellover@daum.net', '$2b$10$N9qo8uLOickgx2ZMRZoMye.IjdJrwQOHdZmQe4rIpOkUmKxcs6MQi', '강원도 강릉시', '경강로 528', 'local'),
('샌드위치마스터', 'sandwichmaster@gmail.com', '$2b$10$N9qo8uLOickgx2ZMRZoMye.IjdJrwQOHdZmQe4rIpOkUmKxcs6MQi', '충청북도 충주시', '중앙탑면 중앙탑로 639', 'local'),
('샐러드킹', 'saladking@naver.com', '$2b$10$N9qo8uLOickgx2ZMRZoMye.IjdJrwQOHdZmQe4rIpOkUmKxcs6MQi', '충청남도 아산시', '온천대로 741', 'local'),
('스테이크러버', 'steaklover@gmail.com', '$2b$10$N9qo8uLOickgx2ZMRZoMye.IjdJrwQOHdZmQe4rIpOkUmKxcs6MQi', '전라북도 익산시', '인북로 852', 'local'),
('리조또마니아', 'risottomania@daum.net', '$2b$10$N9qo8uLOickgx2ZMRZoMye.IjdJrwQOHdZmQe4rIpOkUmKxcs6MQi', '전라남도 목포시', '하당대로 963', 'local'),
('그라탕킹', 'gratinking@gmail.com', '$2b$10$N9qo8uLOickgx2ZMRZoMye.IjdJrwQOHdZmQe4rIpOkUmKxcs6MQi', '경상북도 포항시', '북구 중앙로 174', 'local'),
('오므라이스러버', 'omuraislover@naver.com', '$2b$10$N9qo8uLOickgx2ZMRZoMye.IjdJrwQOHdZmQe4rIpOkUmKxcs6MQi', '경상남도 진주시', '진주대로 285', 'local'),
('카레마스터', 'currymaster@gmail.com', '$2b$10$N9qo8uLOickgx2ZMRZoMye.IjdJrwQOHdZmQe4rIpOkUmKxcs6MQi', '제주특별자치도 서귀포시', '중문관광로 396', 'local'),
('우동킹', 'udonking@daum.net', '$2b$10$N9qo8uLOickgx2ZMRZoMye.IjdJrwQOHdZmQe4rIpOkUmKxcs6MQi', '서울특별시 영등포구', '여의도동로 417', 'local'),
('소바러버', 'sobalover@gmail.com', '$2b$10$N9qo8uLOickgx2ZMRZoMye.IjdJrwQOHdZmQe4rIpOkUmKxcs6MQi', '서울특별시 동작구', '사당로 528', 'local'),
('라멘마니아', 'ramenmania@naver.com', '$2b$10$N9qo8uLOickgx2ZMRZoMye.IjdJrwQOHdZmQe4rIpOkUmKxcs6MQi', '서울특별시 관악구', '신림로 639', 'local'),
('돈부리킹', 'donburiking@gmail.com', '$2b$10$N9qo8uLOickgx2ZMRZoMye.IjdJrwQOHdZmQe4rIpOkUmKxcs6MQi', '부산광역시 사상구', '사상로 741', 'local'),
('온면러버', 'onmyeonlover@daum.net', '$2b$10$N9qo8uLOickgx2ZMRZoMye.IjdJrwQOHdZmQe4rIpOkUmKxcs6MQi', '인천광역시 서구', '청라국제도시로 852', 'local'),
('비빔밥마스터', 'bibimbapmaster@gmail.com', '$2b$10$N9qo8uLOickgx2ZMRZoMye.IjdJrwQOHdZmQe4rIpOkUmKxcs6MQi', '대구광역시 북구', '칠곡중앙대로 963', 'local'),
('국밥킹', 'gukbapking@naver.com', '$2b$10$N9qo8uLOickgx2ZMRZoMye.IjdJrwQOHdZmQe4rIpOkUmKxcs6MQi', '광주광역시 동구', '제봉로 174', 'local'),
('찌개러버', 'jjigaelover@gmail.com', '$2b$10$N9qo8uLOickgx2ZMRZoMye.IjdJrwQOHdZmQe4rIpOkUmKxcs6MQi', '대전광역시 동구', '대동로 285', 'local');